### PR TITLE
chore: add package-lock and update tsconfig

### PR DESCRIPTION
**Pull request by agileurbanite**
Typescript complains that variables in catch are unknown.  Updated package-lock to use typescript 4.4.4 (latest) which introduces a new compiler option in TS 4.4.2 to allow for variables in catch to be any versus unknown.

We should go through and properly add typeguards in the future but this is to get around the compiler issues of TS for this project.

### CODE REVIEW

**Comment by y04nqt** [comment]
Just tested this locally and works unlike the develop branch currently. I agree. we can definitely look at a more reasonable solution later, but this gets it working 👍🏻

**Comment by y04nqt** [comment]
LGTM 💠

**Comment by agileurbanite** [comment]
Awesome also quick note on including package-lock it ensures that we are all running the same versions of dependencies from contributors to whatever ends up running the build for CICD.  @y04nqt please feel free to merge when ready, I don't have write access to the repo so can't.

**Comment by Severino** [comment]
Need review by @hypnagonia

**Comment by agileurbanite** [comment]
@Severino can you add @hypnagonia as a reviewer to this PR?  I can't do that and assign the PR.

**Comment by Severino** [comment]
No, I have no permissions in here.

**Pull request closed without merging**
